artifact_location: /Users/zla0368/Documents/RL/RL_Class/code/test_hw/week-2-build-your-own-ppo-heng4str/submission/mlflow/0
creation_time: 1694832014329
experiment_id: '0'
last_update_time: 1694832014329
lifecycle_stage: active
name: Default
