artifact_location: /Users/zla0368/Documents/RL/RL_Class/code/test_hw/week-2-build-your-own-ppo-heng4str/submission/mlflow/785388840261714606
creation_time: 1694832014343
experiment_id: '785388840261714606'
last_update_time: 1694894040459
lifecycle_stage: deleted
name: my_experiment
tags: {}
