artifact_uri: /Users/zla0368/Documents/RL/RL_Class/code/test_hw/week-2-build-your-own-ppo-heng4str/submission/mlflow/785388840261714606/33b314e55d1b4262aa6bcb5f990bb53d/artifacts
deleted_time: 1694894040459
end_time: null
entry_point_name: ''
experiment_id: '785388840261714606'
lifecycle_stage: deleted
run_id: 33b314e55d1b4262aa6bcb5f990bb53d
run_name: PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-1v1_5d101_00000
run_uuid: 33b314e55d1b4262aa6bcb5f990bb53d
source_name: ''
source_type: 4
source_version: ''
start_time: 1694832035037
status: 1
tags: []
user_id: unknown
